### ISSUE TITLE
Footer Design to be implemented

### ISSUE THREAD

**Issue by tanwarAalok** [tanwarAalok/VITBuzz#2]
![image](https://user-images.githubusercontent.com/78805153/226130426-d897cb94-f0a5-44dc-939e-df32950b997d.png)

**Comment by nitin1chandani** [comment]
Assign me , If haven't assigned yet.

**Comment by mukadas026** [comment]
@tanwarAalok please assign this issue to me

**Comment by tanwarAalok** [comment]
> Assign me , If haven't assigned yet.

> Assigning this task to you.

**Comment by tanwarAalok** [comment]
> Assign me , If haven't assigned yet.

@nitin1chandani  I have asssigned the task to you, complete it as soon as possible.

**Comment by mukadas026** [comment]
@tanwarAalok I'm a bit occupied with school projects....will do as soon as possible
